#!/usr/bin/env python3
"""Validate outputs generated by generate_visual_map_v2.py."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT_ROOT = ROOT / "prototype_visual_maps" / "template_system_tests"
DUNGEON_REVIEW = ROOT / "prototype_visual_maps" / "dungeon_review"
REPORTS = ROOT / "reports"

import sys
sys.path.insert(0, str(ROOT))
import validate_mine_visual_patterns  # noqa: E402


def load(path: Path):
    return json.loads(path.read_text(encoding="utf-8"))


def validate_marker_folder(path: Path) -> dict:
    errors = []
    warnings = []
    semantic = path / "semantic.json"
    metadata = path / "metadata.json"
    if not semantic.exists():
        errors.append("missing semantic.json")
    else:
        try:
            doc = load(semantic)
            grid = doc.get("semanticGrid", [])
            flat = [c for row in grid for c in row]
            if "marker_entrance" not in flat:
                errors.append("missing marker_entrance")
            if "marker_exit" not in flat:
                errors.append("missing marker_exit")
        except Exception as exc:
            errors.append(f"semantic.json parse failed: {exc}")
    if not metadata.exists():
        errors.append("missing metadata.json")
    else:
        try:
            meta = load(metadata)
            if meta.get("productionOutput") is not False:
                errors.append("marker fallback metadata must set productionOutput false")
            if meta.get("tile946Status") != "not_used":
                errors.append("tile946Status must be not_used")
        except Exception as exc:
            errors.append(f"metadata parse failed: {exc}")
    for name in ("preview_clean.png", "preview_labeled.png", "validation_report.md"):
        if not (path / name).exists():
            errors.append(f"missing {name}")
    return {"path": str(path.resolve()), "status": "PASS" if not errors else "FAIL", "errors": errors, "warnings": warnings}


def validate_visual_folder(path: Path) -> dict:
    errors = []
    warnings = []
    tmx_files = sorted(path.glob("*.tmx"))
    if not tmx_files:
        errors.append("missing TMX output")
        return {"path": str(path.resolve()), "status": "FAIL", "errors": errors, "warnings": warnings}
    mine_results = []
    for tmx in tmx_files:
        result = validate_mine_visual_patterns.validate_map(tmx)
        mine_results.append(result)
        errors += [f"{tmx.name}: {e}" for e in result.get("errors", [])]
        warnings += [f"{tmx.name}: {w}" for w in result.get("warnings", [])]
    metadata = path / "metadata.json"
    if metadata.exists():
        meta = load(metadata)
        if meta.get("productionOutput") is not False:
            errors.append("visual template test must be prototype output, not production")
        if not meta.get("resolvedTemplates"):
            errors.append("metadata missing resolvedTemplates")
    else:
        errors.append("missing metadata.json")
    return {"path": str(path.resolve()), "status": "PASS" if not errors else "FAIL", "errors": errors, "warnings": warnings, "mineResults": mine_results}


def main() -> int:
    checks = []
    for folder in [
        OUT_ROOT / "dungeon_mine_template_test_marker_fallback",
        OUT_ROOT / "outdoor_template_test_marker_fallback",
        OUT_ROOT / "indoor_template_test_marker_fallback",
    ]:
        checks.append(validate_marker_folder(folder))
    checks.append(validate_visual_folder(OUT_ROOT / "dungeon_mine_template_test_visual"))
    custom_tmx = DUNGEON_REVIEW / "custom_03" / "custom_03_template_fixed.tmx"
    custom_result = validate_mine_visual_patterns.validate_map(custom_tmx) if custom_tmx.exists() else {"status": "FAIL", "errors": ["missing custom_03_template_fixed.tmx"], "warnings": []}
    checks.append({
        "path": str(custom_tmx.resolve()),
        "status": custom_result["status"],
        "errors": custom_result.get("errors", []),
        "warnings": custom_result.get("warnings", []),
        "mineResults": [custom_result],
    })
    status = "PASS" if all(c["status"] == "PASS" for c in checks) else "FAIL"
    REPORTS.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Visual Template Output Validation",
        "",
        f"- Status: {status}",
        "",
        "| Output | Status | Errors | Warnings |",
        "|---|---:|---:|---:|",
    ]
    for c in checks:
        lines.append(f"| `{Path(c['path']).name}` | {c['status']} | {len(c['errors'])} | {len(c['warnings'])} |")
    for c in checks:
        if c["errors"] or c["warnings"]:
            lines += ["", f"## {c['path']}"]
            lines += [f"- ERROR: {e}" for e in c["errors"]]
            lines += [f"- WARNING: {w}" for w in c["warnings"][:50]]
    if status == "PASS":
        lines += ["", "All template-system prototype outputs validated."]
    report = REPORTS / "visual_template_output_validation_report.md"
    report.write_text("\n".join(lines) + "\n", encoding="utf-8")
    (REPORTS / "visual_template_output_validation_report.json").write_text(json.dumps({"status": status, "checks": checks}, indent=2), encoding="utf-8")
    print(json.dumps({"status": status, "checks": len(checks), "report": str(report.resolve())}, indent=2))
    return 0 if status == "PASS" else 1


if __name__ == "__main__":
    raise SystemExit(main())
